/*
 * Generates public/sitemap.xml and public/robots.txt.
 *
 * Slugs are read out of the catalogue with a regex rather than by importing
 * it, because the catalogue is TypeScript and this runs as plain node in
 * `prebuild`. It is a brittle way to read a module and it is the right trade
 * here: the alternative is a build step whose only job is to let one script
 * read one array. The sanity check below fails loudly if the shape changes,
 * so it cannot silently start emitting an empty sitemap.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const SITE = 'https://kipekee-creations.vercel.app'

/** Routes with no parameters, and how much each is worth to a crawler. */
const STATIC = [
  ['/', 1.0],
  ['/shop', 0.9],
  ['/custom-curtains', 0.8],
  ['/hotel-linen', 0.8],
  ['/measure-guide', 0.6],
  ['/about', 0.5],
  ['/contact', 0.5],
  ['/quote', 0.4],
  ['/returns', 0.3],
  ['/terms', 0.2],
  ['/privacy', 0.2],
]

/** Everything a crawler should never be offered. */
const DISALLOW = [
  '/admin',
  '/account',
  '/checkout',
  '/login',
  '/register',
  '/forgot-password',
  '/reset-password',
  '/accept-invite',
  '/change-password',
  '/no-access',
]

const main = async () => {
  const source = await readFile(resolve(ROOT, 'src/data/catalogue.ts'), 'utf8')
  const slugs = [...source.matchAll(/^ {4}slug: '([a-z0-9-]+)',$/gm)].map((m) => m[1])

  if (slugs.length < 10) {
    console.error(
      `sitemap: found only ${slugs.length} product slugs in catalogue.ts. The file shape has probably changed.`,
    )
    process.exit(1)
  }

  const today = new Date().toISOString().slice(0, 10)
  const url = (path, priority) =>
    `  <url>\n    <loc>${SITE}${path}</loc>\n    <lastmod>${today}</lastmod>\n    <priority>${priority}</priority>\n  </url>`

  const body = [
    ...STATIC.map(([path, priority]) => url(path, priority.toFixed(1))),
    ...slugs.map((slug) => url(`/product/${slug}`, '0.7')),
  ].join('\n')

  await writeFile(
    resolve(ROOT, 'public/sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`,
  )

  await writeFile(
    resolve(ROOT, 'public/robots.txt'),
    [
      '# Generated by scripts/seo/sitemap.mjs. Do not edit by hand.',
      'User-agent: *',
      ...DISALLOW.map((path) => `Disallow: ${path}`),
      '',
      `Sitemap: ${SITE}/sitemap.xml`,
      '',
    ].join('\n'),
  )

  console.log(
    `Wrote sitemap.xml (${STATIC.length + slugs.length} urls, ${slugs.length} products) and robots.txt`,
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
