import { mkdir, readdir, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { render } from '@react-email/render'

/**
 * Renders every template in `templates/` to a static Qute template in the
 * backend.
 *
 * The templates are React, but nothing renders React at send time: Quarkus owns
 * sending, and standing up a Node service purely to interpolate a name into a
 * greeting would mean a second runtime to deploy and monitor for no benefit. So
 * React is the authoring tool and Qute is the runtime, and this script is the
 * one place the two meet. Re-run it after any template change and commit the
 * output alongside, because the backend builds from the committed HTML and
 * never from this workspace.
 */

const here = dirname(fileURLToPath(import.meta.url))
const DEFAULT_OUT = resolve(here, '../../kipekee-creations-backend/src/main/resources/templates/email')

const outArg = process.argv.indexOf('--out')
const outDir = outArg === -1 ? DEFAULT_OUT : resolve(process.argv[outArg + 1]!)

const BANNER = (source: string) =>
  `<!-- Generated from kipekee-creations/emails/templates/${source} by \`npm run build\` in that workspace. Do not edit this file directly, the next render overwrites it. -->\n`

/**
 * `{#for}` and friends are emitted by the React templates as plain text nodes,
 * which puts them inside whichever element wrapped them. A section tag that
 * came out wrapped in a `<p>` would put a stray empty paragraph in every
 * message and, worse, split the loop across the element it is meant to repeat.
 * Hoisting them onto their own line is cosmetic; the assertion below is not.
 */
const TAG = /\{(#(?:for|if|else|let)\b[^}]*|\/(?:for|if|let))\}/g

function checkTagsBalance(html: string, name: string) {
  let depth = 0
  for (const [, tag] of html.matchAll(TAG)) {
    if (tag.startsWith('/')) depth -= 1
    else if (!tag.startsWith('#else')) depth += 1
  }
  if (depth !== 0) {
    throw new Error(
      `${name}: Qute section tags are unbalanced (depth ${depth}). ` +
        'Every <S t="#for ..." /> needs a matching <S t="/for" />.',
    )
  }
}

/**
 * React escapes `&` in attributes, `<` and `>` in text. Qute delimiters survive
 * that untouched, but an escaped one would silently become literal text in the
 * sent message rather than an interpolation, so fail loudly instead.
 */
function checkNoEscapedDelimiters(html: string, name: string) {
  const broken = html.match(/&#x7[bd];|&lbrace;|&rbrace;/i)
  if (broken) {
    throw new Error(`${name}: a Qute delimiter came out HTML-escaped (${broken[0]}).`)
  }
}

const templates = (await readdir(join(here, 'templates')))
  .filter((f) => f.endsWith('.tsx'))
  .sort()

if (templates.length === 0) throw new Error('No templates found.')

await mkdir(outDir, { recursive: true })

for (const file of templates) {
  const name = file.replace(/\.tsx$/, '')
  const mod = await import(join(here, 'templates', file))
  const Template = mod.default
  if (typeof Template !== 'function') {
    throw new Error(`${file}: expected a default-exported component.`)
  }

  const html = await render(<Template />)
  checkNoEscapedDelimiters(html, file)
  checkTagsBalance(html, file)

  await writeFile(join(outDir, `${name}.html`), BANNER(file) + html, 'utf8')

  // A text alternative, so the message is multipart and does not read as
  // markup to a client that refuses HTML, or to a spam filter that scores
  // HTML-only mail. Wrapping is off because a wrapped `{#for line in lines}`
  // stops being a Qute tag.
  const plain = await render(<Template />, {
    plainText: true,
    htmlToTextOptions: { wordwrap: false },
  })
  checkNoEscapedDelimiters(plain, `${file} (text)`)
  await writeFile(join(outDir, `${name}.txt`), plain, 'utf8')

  console.log(`  ${name}.html  ${(html.length / 1024).toFixed(1)} kB`)
}

console.log(`\n${templates.length} templates rendered to ${outDir}`)
